<a href="https://colab.research.google.com/github/engmahaq8/The_AI_Engineer/blob/main/Copy_of_intro_to_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

### Tensorflow Tensor

In [ ]:
a = tf.constant([3, 3, 3])# define a tf tensor
b = tf.constant([2, 2, 2])  # Define tensors



### Tensorflow Placeholders

**Placeholders (tf.placeholder):**
These were used as inputs to the graph where the values would be provided at runtime via feed_dict.

They allowed dynamic input feeding during the execution of the graph.

**Session:** In TensorFlow 1.x, you needed to create a tf.Session() to run operations, and placeholders required you to feed values into them during session execution.

In [ ]:
import tensorflow as tf

# Instead of using tf.placeholder, use tf.constant or tf.Variable
x = tf.constant(3.0)  # If x is a fixed input

# or
x = tf.Variable(3.0)  # If x needs to be updated during training

# Constant
a = tf.constant(5.0)
b = tf.constant(10.0)

# Define an operation
result = a * x + b

# In TensorFlow 2.x, you don't need a session to run the computation graph
# The result is calculated immediately
print("Result with placeholder:", result)

Result with placeholder: tf.Tensor(25.0, shape=(), dtype=float32)


**TensorFlow 2.x:** Focuses on constants (tf.constant) and variables (tf.Variable).

Eager execution removes the need for placeholders or sessions.

**TensorFlow 1.x:** Used placeholders (tf.placeholder) for feeding data into graphs at runtime and required sessions to execute the graph.

### Tensorflow: Tensor Operations

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
import tensorflow as tf

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [ ]:
print("Is eager execution enable?",tf.executing_eagerly())

Is eager execution enable? True


In [ ]:
a = tf.constant([3, 3, 3])# define a tf tensor
b = tf.constant([2, 2, 2])

In [ ]:
sum_result = tf.add(a, b) # Addition
print("Sum of Tensors",sum_result)

Sum of Tensors tf.Tensor([5 5 5], shape=(3,), dtype=int32)


In [ ]:
sum_result = tf.add(a, b) # Addition
diff_result = tf.subtract(a, b) # Subtraction
quot_result = tf.divide(a, b) # Division
prod_result = tf.multiply(a, b) # Multiplication

print("Sum of Tensors",sum_result)
print("Difference of tensors",diff_result)
print("Quotient of Tensor",quot_result)
print("Product of tensors ",prod_result)




Sum of Tensors tf.Tensor([5 5 5], shape=(3,), dtype=int32)
Difference of tensors tf.Tensor([1 1 1], shape=(3,), dtype=int32)
Quotient of Tensor tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64)
Product of tensors  tf.Tensor([6 6 6], shape=(3,), dtype=int32)


In [ ]:
# Element-wise operations
min_result = tf.minimum(a, b)
max_result = tf.maximum(a, b)
abs_result = tf.abs(a)

print("Minimum:", min_result)
print("Maximum:", max_result)
print("Absolute value:", abs_result)


Minimum: tf.Tensor([2 2 2], shape=(3,), dtype=int32)
Maximum: tf.Tensor([3 3 3], shape=(3,), dtype=int32)
Absolute value: tf.Tensor([3 3 3], shape=(3,), dtype=int32)


In [ ]:
c=tf.constant([-1,-2,1])
tf.abs(c)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 1], dtype=int32)>

In [ ]:
# Cast the tensor `a` to float32 to match the type of 1e-8
a = tf.cast(a, dtype=tf.float32)

# Now you can safely compute the logarithm
log_result = tf.math.log(tf.maximum(a, 1e-8))  # Ensure positive values for logarithm
exp_result = tf.exp(a)


print("Logarithm:", log_result)
print("Exponential:", exp_result)


Logarithm: tf.Tensor([1.0986123 1.0986123 1.0986123], shape=(3,), dtype=float32)
Exponential: tf.Tensor([20.085537 20.085537 20.085537], shape=(3,), dtype=float32)


In [ ]:
a = tf.constant([3, 3, 3])

scalar = tf.constant(2)
broadcast_result = tf.add(a, scalar)
print("Broadcasted Addition:", broadcast_result)

Broadcasted Addition: tf.Tensor([5 5 5], shape=(3,), dtype=int32)


In [ ]:
sum_axis = tf.reduce_sum(a, axis=0)  # Sum across the first axis
mean_axis = tf.reduce_mean(a, axis=0)  # Mean across the first axis
print("Sum across axis 0:", sum_axis)
print("Mean across axis 0:", mean_axis)

Sum across axis 0: tf.Tensor(9, shape=(), dtype=int32)
Mean across axis 0: tf.Tensor(3, shape=(), dtype=int32)


#### Matmul example

In [ ]:
import tensorflow as tf

# Example: Input data for a neural network layer
input_data = tf.constant([[1.0, 2.0], [3.0, 4.0]])  # Shape: (2, 2)
weights = tf.constant([[0.5, -1.0], [1.0, 2.0]])    # Shape: (2, 2)

# Matrix multiplication between input and weights
output = tf.matmul(input_data, weights)
print("Neural Network Layer Output:\n", output)

Neural Network Layer Output:
 tf.Tensor(
[[2.5 3. ]
 [5.5 5. ]], shape=(2, 2), dtype=float32)


#### Multiply Example (Element Wise)

In [ ]:
import tensorflow as tf

# Example: Simulating image pixel values
image = tf.constant([[255, 128], [64, 32]], dtype=tf.float32)  # Shape: (2, 2)

# Scaling factor for each pixel (element-wise multiplication)
#for example, you want to minimize the size of the image by halfw
scaling_factor = 0.5
scaled_image = tf.multiply(image, scaling_factor)
print("Scaled Image:\n", scaled_image)


Scaled Image:
 tf.Tensor(
[[127.5  64. ]
 [ 32.   16. ]], shape=(2, 2), dtype=float32)


#### Multiply Example

#### Gradient Derivates

In [ ]:
x = tf.Variable(1.0)

def f(x):
  y = x**2 + 2*x - 5
  return y

In [ ]:
with tf.GradientTape() as tape:
  y = f(x)

g_x = tape.gradient(y, x)  # g(x) = dy/dx

g_x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

### Tensorflow: Tensor vs Numpy Ndarray
Let's do some benchmarking

In [ ]:
import time
import numpy as np
import tensorflow as tf

# Create large random matrices
size = 10000
np_matrix_a = np.random.randn(size, size)
np_matrix_b = np.random.randn(size, size)
tf_matrix_a = tf.random.normal((size, size))
tf_matrix_b = tf.random.normal((size, size))

# Benchmark NumPy
start_time = time.time()
np_result = np.dot(np_matrix_a, np_matrix_b)
np_duration = time.time() - start_time

# Benchmark TensorFlow on CPU
start_time = time.time()
tf_result = tf.matmul(tf_matrix_a, tf_matrix_b)
tf_duration = time.time() - start_time

print("NumPy Duration: {:.6f} seconds".format(np_duration))
print("TensorFlow (CPU) Duration: {:.6f} seconds".format(tf_duration))


NumPy Duration: 60.150858 seconds
TensorFlow (CPU) Duration: 35.363475 seconds


In [ ]:
# Example forward propagation in Python
def forward_propagation(X, W, b):
    Z = np.dot(W, X) + b  # Weighted sum
    A = 1 / (1 + np.exp(-Z))  # Sigmoid activation function
    return A

# Dummy data
X = np.array([[1.0], [2.0], [3.0]])  # Input
W = np.array([[0.2, 0.4, 0.6]])  # Weights
b = np.array([[0.5]])  # Bias

# Forward propagation
output = forward_propagation(X, W, b)
print("Output of forward propagation:", output)

Output of forward propagation: [[0.96442881]]


In [ ]:

# Example forward propagation in Python
def forward_propagation(X, W, b):
    Z = np.dot(W, X) + b  # Weighted sum
    A = 1 / (1 + np.exp(-Z))  # Sigmoid activation function
    return A

# Dummy data
X = np.array([[1.0], [2.0], [3.0]])  # Input
W = np.array([[0.2, 0.4, 0.6]])  # Weights
b = np.array([[0.5]])  # Bias

# Forward propagation
output = forward_propagation(X, W, b)
print("Output of forward propagation:", output)


In [ ]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# ReLU activation function
def relu(x):
    return np.maximum(0, x)

# Tanh activation function
def tanh(x):
    return np.tanh(x)

# Example of activation functions
x = np.array([-1.0, 0.0, 1.0, 2.0])
print("Sigmoid:", sigmoid(x))
print("ReLU:", relu(x))
print("Tanh:", tanh(x))


Sigmoid: [0.26894142 0.5        0.73105858 0.88079708]
ReLU: [0. 0. 1. 2.]
Tanh: [-0.76159416  0.          0.76159416  0.96402758]


In [ ]:
def forward_with_activation(X, W, b, activation_function):
    Z = np.dot(W, X) + b  # Weighted sum
    match activation_function:
        case 'sigmoid':
            A = sigmoid(Z)
        case 'relu' :
            A = relu(Z)
        case 'tanh' :
            A = tanh(Z)
    return A

# Testing the function
W = np.array([[0.2, 0.4, 0.6]])
b = np.array([[0.5]])
X = np.array([[1.0], [2.0], [3.0]])

output = forward_with_activation(X, W, b, activation_function='relu')
print("Output with ReLU activation:", output)


Output with ReLU activation: [[3.3]]
